"""empty message

Revision ID: 56a43c63aac3
Revises: 
Create Date: 2023-10-16 21:29:58.142297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a43c63aac3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_request')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_request',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('agent_id', sa.INTEGER(), nullable=True),
    sa.Column('pickup_address', sa.VARCHAR(length=200), nullable=False),
    sa.Column('pickup_time', sa.DATETIME(), nullable=False),
    sa.Column('item_description', sa.VARCHAR(length=50), nullable=False),
    sa.Column('delivery_address', sa.VARCHAR(length=200), nullable=False),
    sa.Column('delivery_time', sa.DATETIME(), nullable=False),
    sa.Column('delivery_instruction', sa.VARCHAR(length=400), nullable=True),
    sa.Column('order_status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('id', sa.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['delivery_agent.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
