"""empty message

Revision ID: bbd01aef5680
Revises: 182df592a306
Create Date: 2023-10-22 12:32:09.282732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd01aef5680'
down_revision = '182df592a306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_request',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('pickup_address', sa.String(length=200), nullable=False),
    sa.Column('pickup_time', sa.DateTime(), nullable=False),
    sa.Column('item_description', sa.String(length=50), nullable=False),
    sa.Column('contact_person', sa.String(length=50), nullable=False),
    sa.Column('contact_phone_number', sa.String(length=15), nullable=False),
    sa.Column('delivery_address', sa.String(length=200), nullable=False),
    sa.Column('delivery_time', sa.DateTime(), nullable=False),
    sa.Column('delivery_instruction', sa.String(length=400), nullable=True),
    sa.Column('estimated_distance', sa.String(length=15), nullable=False),
    sa.Column('estimated_duration', sa.String(length=15), nullable=False),
    sa.Column('delivery_cost', sa.String(length=20), nullable=False),
    sa.Column('order_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['delivery_agent.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_request')
    # ### end Alembic commands ###
